//get all doms needed
var gridNumInput = document.getElementsByClassName("gridNumInput")[0];
var genGridBtn = document.getElementById("genGridBtn");
var gridContainer = document.getElementsByClassName("gridContainer")[0];

//add event handler for the button
genGridBtn.addEventListener("click", generateGrids, false);
//add event handler to output the number using event delegation
gridContainer.addEventListener("click", writeNumber, false);

function generateGrids() {
	//remove old grids
	gridContainer.innerHTML = null;
	//add new grids
	var num = gridNumInput.value;
	for(var i = 0; i < num * num; i++) {
		createOneGrid(i);	
	}
}

//Create a new grid under "gridContainer" div
function createOneGrid(num) {
	var grid = document.createElement("button");
	grid.className = "grid";
	grid.innerHTML = num;
	gridContainer.appendChild(grid);
}

function writeNumber(event) {
	//test if the event is truely generated by grids
	if (event.target.tagName === "BUTTON") {
		var number = event.target.innerHTML;
		console.log(number);
	}
}



